### PR TITLE
Convert to oxlib points

### PR DESCRIPTION
**Pull request by TonybynMp4**

### CODE REVIEW

**Comment by ARSSANTO** [comment]
1st if i enable debug mode its crash the server

**Comment by ARSSANTO** [comment]
https://github.com/TonybynMp4/qbx-garages/blob/a7705e38c7dfba4d8062c0f3385087ea85393562/client/main.lua#L919

change it too 

`exports['qb-core']:DrawText(Config.Garages[CurrentGarage]['drawText'], Config.DrawTextPosition)`


& please 

https://github.com/TonybynMp4/qbx-garages/blob/a7705e38c7dfba4d8062c0f3385087ea85393562/config.lua#L110

Config.DrawTextPosition = 'left-center' -- location of drawtext: left-center, top-center, right-center i forget to do so

**Comment by TonybynMp4** [comment]
> https://github.com/TonybynMp4/qbx-garages/blob/a7705e38c7dfba4d8062c0f3385087ea85393562/client/main.lua#L919
> change it too
> `exports['qb-core']:DrawText(Config.Garages[CurrentGarage]['drawText'], Config.DrawTextPosition)`
No ? this is for qbx-core, the export is in qbx-core
it may be qb-core for you if you didn't change it but it's still qbx-core for (almost) everyone else

**Comment by ARSSANTO** [comment]
i mean to say Config.Garages[CurrentGarage]['drawText'] this part

**Comment by TonybynMp4** [comment]
oh..

**Comment by ARSSANTO** [comment]
radial menu option also not removing while getting  outside of zone

**Comment by TonybynMp4** [comment]
> radial menu option also not removing while getting outside of zone

should be good now, i forgor that part lol

**Comment by TonybynMp4** [comment]
> 1st if i enable debug mode its crash the server

No idea why that happens, it works fine on my end, tried both the lib zone debug and a garage's debug.

**Comment by JonasDev17** [comment]
Merge conflict has to be resolved and the following function needs a better name:

```
local function SetCurrentGarage()
    CurrentGarage = nil
end
```

I would probably name it something like "ResetCurrentGarage"

**Comment by TonybynMp4** [comment]
Done 👍🏻

**Comment by JonasDev17** [comment]
> Done 👍🏻

I added another comment because you didn't properly resolve the merge conflict

**Pull request merged**
